### ISSUE TITLE
Switching to Material theme breaks UI and ability to revert theme

### ISSUE THREAD

**Issue by AsukaGaming** [elkorol/Stash-App-Theme-Switch-Plugin#4]
Hey, great plugin but it has an issue with the material theme. On a new Stash docker container, activating the plugin and switching to the material theme prevents the menu from reopening and therefore prevents changing the theme again. 
Uninstalling and reinstalling the plugin does not appear to fix the issue.

The following images are an attempt to open the menu
before clicking the menu button:
![image](https://github.com/elkorol/Stash-App-Theme-Switch-Plugin/assets/154099144/ef2be8c9-8e0c-404f-b3d2-fa9040983ff0)
after clicking the menu button:
![image](https://github.com/elkorol/Stash-App-Theme-Switch-Plugin/assets/154099144/d8381de3-1d36-4124-906f-8d75d545b059)

**Comment by elkorol** [comment]
Hey thanks, it should be fixed now. It is also available in the community repo, someone updated it, so it isn't hardcoded css. But it has a couple of issues that need fixed there I believe
